INSERT INTO [PG1].[otusproject].[dbo].[cachetechinfohist]
           ([ID] ,[OwnerID] ,[TenantryID] ,[CargoID] ,[TechnicalDataSourceID]
           ,[VehicleID] ,[VehicleNumber] ,[DocumentNumber] ,[OriginalCountryID] ,[VehicleModelID] ,[Capacity] ,[TareWeight] ,[Caliber]
           ,[NextMaintenanceDate] ,[MileageFlag] ,[Mileage] 
           ,[NextOwnerRecertification] ,[BuildDate] ,[FactoryOfOriginID] ,[MaintenanceAgreement]
           ,[DateFrom] ,[DateTill] ,[DocTypeID] 
           ,[TechnicalActID] ,[TechnicalActVehicleID]
           ,[FieldsUpdatedDocumentVehicleID]
           ,[OrdinalFrom] ,[NextCoatingDate] ,[EnvelopeModernizationDate])
SELECT [ID]
    ,[OwnerID]
    ,[TenantryID]
    ,[CargoID]
    ,[TechnicalDataSourceID]
    ,[VehicleID]
    ,cast([VehicleNumber] as nvarchar(8)) as [VehicleNumber]
    ,cast([DocumentNumber] as nvarchar(64)) as [DocumentNumber]
    ,[OriginalCountryID]
    ,[VehicleModelID]
    ,[Capacity]
    ,[TareWeight]
    ,[Caliber]
    ,[NextMaintenanceDate]
    ,[MileageFlag]
    ,[Mileage]
    ,[NextOwnerRecertification]
    ,[BuildDate]
    ,[FactoryOfOriginID]
    ,cast([MaintenanceAgreement] as nvarchar(255)) as [MaintenanceAgreement]
    ,[DateFrom]
    ,[DateTill]
    ,[DocTypeID]
    ,[TechnicalActID]
    ,[TechnicalActVehicleID]
    ,cast([FieldsUpdatedDocumentVehicleID] as nvarchar(2048)) as [FieldsUpdatedDocumentVehicleID]
    ,[OrdinalFrom]
    ,[NextCoatingDate]
    ,[EnvelopeModernizationDate]
FROM [dbo].[cachetechinfohist]
